[toolchain]
anchor_version = "0.32.1"
solana_version = "3.0.13"

[features]
resolution = true
skip-lint = false

[programs.devnet]
kamiyo = "3ZYPtFBF8rfRYvLi5QUnU4teHPzFEpHuz6dUZry9FRKr"
hive = "DqEHULYq79diHGa4jKNdBnnQR4Ge8zAfYiRYzPHhF5Km"
kamiyo_staking = "9QZGdEZ13j8fASEuhpj3eVwUPT4BpQjXSabVjRppJW2N"
kamiyo_escrow = "FVnvAs8bahMwAvjcLq5ZrXksuu5Qeu2MRkbjwB9mua3u"
kamiyo_governance = "E3oQcCm55mykVG1A92qGvgWQdxv8TmkpvWwat1NCFGav"
kamiyo_transfer_hook = "4p9eHUGsx93XC5i6y9fL3cbTs5Zpfqidjjd1e41FQaU6"
kamiyo_fast_voting = "AakwnBstczs5KC2jKPfBuFLQZADXrx4oPH8FtJbhPxwA"
meishi = "6uejE3hDz3ZNHW7P4uHQEHS6fHAQ4vLJg7rx4VBYwpyK"

[programs.localnet]
kamiyo = "3ZYPtFBF8rfRYvLi5QUnU4teHPzFEpHuz6dUZry9FRKr"
hive = "DqEHULYq79diHGa4jKNdBnnQR4Ge8zAfYiRYzPHhF5Km"
kamiyo_staking = "9QZGdEZ13j8fASEuhpj3eVwUPT4BpQjXSabVjRppJW2N"
kamiyo_escrow = "FVnvAs8bahMwAvjcLq5ZrXksuu5Qeu2MRkbjwB9mua3u"
kamiyo_governance = "E3oQcCm55mykVG1A92qGvgWQdxv8TmkpvWwat1NCFGav"
kamiyo_transfer_hook = "4p9eHUGsx93XC5i6y9fL3cbTs5Zpfqidjjd1e41FQaU6"
kamiyo_fast_voting = "AakwnBstczs5KC2jKPfBuFLQZADXrx4oPH8FtJbhPxwA"
meishi = "6uejE3hDz3ZNHW7P4uHQEHS6fHAQ4vLJg7rx4VBYwpyK"

[programs.mainnet]
kamiyo = "3ZYPtFBF8rfRYvLi5QUnU4teHPzFEpHuz6dUZry9FRKr"
hive = "DqEHULYq79diHGa4jKNdBnnQR4Ge8zAfYiRYzPHhF5Km"
kamiyo_staking = "9QZGdEZ13j8fASEuhpj3eVwUPT4BpQjXSabVjRppJW2N"
kamiyo_escrow = "FVnvAs8bahMwAvjcLq5ZrXksuu5Qeu2MRkbjwB9mua3u"
kamiyo_governance = "E3oQcCm55mykVG1A92qGvgWQdxv8TmkpvWwat1NCFGav"
kamiyo_transfer_hook = "4p9eHUGsx93XC5i6y9fL3cbTs5Zpfqidjjd1e41FQaU6"
kamiyo_fast_voting = "AakwnBstczs5KC2jKPfBuFLQZADXrx4oPH8FtJbhPxwA"
meishi = "6uejE3hDz3ZNHW7P4uHQEHS6fHAQ4vLJg7rx4VBYwpyK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx node_modules/mocha/bin/mocha.js -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
shutdown_wait = 2000
upgradeable = false
