#!/bin/bash
# Mitama Mainnet Setup Script
# This script configures the environment for mainnet deployment

set -e

echo "==================================="
echo "Mitama Mainnet Setup"
echo "==================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo ""
echo "Checking prerequisites..."

# Check Solana CLI
if ! command -v solana &> /dev/null; then
    echo -e "${RED}Error: Solana CLI is not installed${NC}"
    echo "Install from: https://docs.solana.com/cli/install-solana-cli-tools"
    exit 1
fi
echo -e "${GREEN}✓ Solana CLI installed${NC}"

# Check Anchor CLI
if ! command -v anchor &> /dev/null; then
    echo -e "${RED}Error: Anchor CLI is not installed${NC}"
    echo "Install from: https://www.anchor-lang.com/docs/installation"
    exit 1
fi
echo -e "${GREEN}✓ Anchor CLI installed${NC}"

# Check Solana version
SOLANA_VERSION=$(solana --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
echo "  Solana version: $SOLANA_VERSION"

# Check Anchor version
ANCHOR_VERSION=$(anchor --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
echo "  Anchor version: $ANCHOR_VERSION"

# RPC Configuration
echo ""
echo "==================================="
echo "RPC Configuration"
echo "==================================="

echo -e "${YELLOW}Select RPC provider for mainnet:${NC}"
echo "1) Helius (Recommended)"
echo "2) QuickNode"
echo "3) Triton"
echo "4) Custom URL"
echo "5) Public RPC (Not recommended for production)"

read -p "Enter choice [1-5]: " rpc_choice

case $rpc_choice in
    1)
        read -p "Enter your Helius API key: " HELIUS_KEY
        RPC_URL="https://mainnet.helius-rpc.com/?api-key=$HELIUS_KEY"
        ;;
    2)
        read -p "Enter your QuickNode endpoint URL: " RPC_URL
        ;;
    3)
        read -p "Enter your Triton endpoint URL: " RPC_URL
        ;;
    4)
        read -p "Enter custom RPC URL: " RPC_URL
        ;;
    5)
        RPC_URL="https://api.mainnet-beta.solana.com"
        echo -e "${YELLOW}Warning: Public RPC has rate limits. Use a dedicated provider for production.${NC}"
        ;;
    *)
        echo "Invalid choice"
        exit 1
        ;;
esac

# Configure Solana CLI
echo ""
echo "Configuring Solana CLI..."
solana config set --url "$RPC_URL"

# Verify connection
echo "Testing RPC connection..."
if solana cluster-version &> /dev/null; then
    CLUSTER_VERSION=$(solana cluster-version)
    echo -e "${GREEN}✓ Connected to mainnet ($CLUSTER_VERSION)${NC}"
else
    echo -e "${RED}Error: Could not connect to RPC${NC}"
    exit 1
fi

# Wallet Configuration
echo ""
echo "==================================="
echo "Wallet Configuration"
echo "==================================="

read -p "Path to deployer keypair [~/.config/solana/id.json]: " DEPLOYER_KEYPAIR
DEPLOYER_KEYPAIR=${DEPLOYER_KEYPAIR:-~/.config/solana/id.json}

if [ ! -f "$DEPLOYER_KEYPAIR" ]; then
    echo -e "${RED}Error: Keypair file not found: $DEPLOYER_KEYPAIR${NC}"
    exit 1
fi

# Set wallet
solana config set --keypair "$DEPLOYER_KEYPAIR"

# Check balance
DEPLOYER_PUBKEY=$(solana-keygen pubkey "$DEPLOYER_KEYPAIR")
BALANCE=$(solana balance "$DEPLOYER_PUBKEY" | grep -oE '[0-9]+\.?[0-9]*')

echo "Deployer: $DEPLOYER_PUBKEY"
echo "Balance: $BALANCE SOL"

if (( $(echo "$BALANCE < 5" | bc -l) )); then
    echo -e "${YELLOW}Warning: Low balance. Recommended minimum: 5 SOL for deployment${NC}"
fi

# Create .env file
echo ""
echo "==================================="
echo "Creating .env file"
echo "==================================="

cat > .env << EOF
# Mitama Mainnet Configuration
# Generated by setup-mainnet.sh on $(date)

SOLANA_CLUSTER=mainnet-beta
SOLANA_RPC_URL=$RPC_URL
MITAMA_PROGRAM_ID=8z97gUtmy43FXLs5kWvqDAA6BjsHYDwKXFoM6LsngXoC
DEPLOYER_KEYPAIR=$DEPLOYER_KEYPAIR

# Token mints
USDC_MINT=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
USDT_MINT=Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
EOF

echo -e "${GREEN}✓ Created .env file${NC}"

# Update Anchor.toml for mainnet
echo ""
echo "Updating Anchor.toml..."
sed -i.bak 's/cluster = "localnet"/cluster = "mainnet"/' Anchor.toml
sed -i.bak "s|wallet = .*|wallet = \"$DEPLOYER_KEYPAIR\"|" Anchor.toml
echo -e "${GREEN}✓ Updated Anchor.toml${NC}"

# Final summary
echo ""
echo "==================================="
echo "Setup Complete"
echo "==================================="
echo ""
echo "Configuration:"
echo "  Cluster: mainnet-beta"
echo "  RPC: $RPC_URL"
echo "  Deployer: $DEPLOYER_PUBKEY"
echo "  Balance: $BALANCE SOL"
echo ""
echo "Next steps:"
echo "  1. Run 'anchor build' to build the program"
echo "  2. Run 'anchor deploy --provider.cluster mainnet' to deploy"
echo "  3. Follow DEPLOYMENT.md for initialization steps"
echo ""
echo -e "${YELLOW}Remember to set up your 2-of-3 multi-sig authority before initializing!${NC}"
