// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Script.sol";
import "../src/AgentRegistry.sol";
import "../src/KamiyoVault.sol";
import "../src/ReputationLimits.sol";

/**
 * @title Deploy
 * @notice Deployment script for Kamiyo Hyperliquid contracts
 * @dev Run with: forge script script/Deploy.s.sol --rpc-url hyperliquid-testnet --broadcast
 */
contract Deploy is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);

        console.log("Deploying from:", deployer);
        console.log("Balance:", deployer.balance);

        vm.startBroadcast(deployerPrivateKey);

        // Deploy AgentRegistry with deployer as initial dispute resolver
        AgentRegistry registry = new AgentRegistry(deployer);
        console.log("AgentRegistry deployed at:", address(registry));

        // Deploy KamiyoVault
        KamiyoVault vault = new KamiyoVault(address(registry), deployer);
        console.log("KamiyoVault deployed at:", address(vault));

        // Deploy ReputationLimits
        ReputationLimits reputationLimits = new ReputationLimits(address(registry), deployer);
        console.log("ReputationLimits deployed at:", address(reputationLimits));

        // Configure AgentRegistry to allow vault to update copiers
        registry.setVault(address(vault));
        console.log("Vault configured in AgentRegistry");

        vm.stopBroadcast();

        // Output deployment summary
        console.log("\n========== DEPLOYMENT SUMMARY ==========");
        console.log("Network: Hyperliquid");
        console.log("Deployer:", deployer);
        console.log("");
        console.log("AgentRegistry:", address(registry));
        console.log("KamiyoVault:", address(vault));
        console.log("ReputationLimits:", address(reputationLimits));
        console.log("");
        console.log("Admin:", deployer);
        console.log("Dispute Resolver:", deployer);
        console.log("=========================================\n");

        // Output for SDK types.ts update
        console.log("// Update packages/kamiyo-hyperliquid/src/types.ts:");
        console.log("contracts: {");
        console.log("  agentRegistry: '%s',", address(registry));
        console.log("  kamiyoVault: '%s',", address(vault));
        console.log("  reputationLimits: '%s',", address(reputationLimits));
        console.log("}");
    }
}

/**
 * @title DeployTestnet
 * @notice Testnet deployment with test configuration
 */
contract DeployTestnet is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);

        console.log("Deploying to TESTNET from:", deployer);

        vm.startBroadcast(deployerPrivateKey);

        AgentRegistry registry = new AgentRegistry(deployer);
        KamiyoVault vault = new KamiyoVault(address(registry), deployer);
        ReputationLimits reputationLimits = new ReputationLimits(address(registry), deployer);
        registry.setVault(address(vault));

        // Set a lower dispute fee for testnet
        vault.setDisputeFee(0.001 ether);

        vm.stopBroadcast();

        console.log("\n========== TESTNET DEPLOYMENT ==========");
        console.log("AgentRegistry:", address(registry));
        console.log("KamiyoVault:", address(vault));
        console.log("ReputationLimits:", address(reputationLimits));
        console.log("Dispute Fee: 0.001 HYPE");
        console.log("=========================================\n");
    }
}

/**
 * @title UploadVK
 * @notice Upload Groth16 verification key to ReputationLimits
 * @dev VK values from circuits/build/verification_key.json
 */
contract UploadVK is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address reputationLimitsAddr = vm.envAddress("REPUTATION_LIMITS");

        // Values from circuits/build/verification_key.json (reputation_threshold circuit)
        // Generated by: node circuits/scripts/export-vk-solidity.js
        uint256[2] memory alpha = [
            uint256(20491192805390485299153009773594534940189261866228447918068658471970481763042),
            uint256(9383485363053290200918347156157836566562967994039712273449902621266178545958)
        ];

        uint256[2][2] memory beta = [
            [uint256(4252822878758300859123897981450591353533073413197771768651442665752259397132),
             uint256(6375614351688725206403948262868962793625744043794305715222011528459656738731)],
            [uint256(21847035105528745403288232691147584728191162732299865338377159692350059136679),
             uint256(10505242626370262277552901082094356697409835680220590971873171140371331206856)]
        ];

        uint256[2][2] memory gamma = [
            [uint256(11559732032986387107991004021392285783925812861821192530917403151452391805634),
             uint256(10857046999023057135944570762232829481370756359578518086990519993285655852781)],
            [uint256(4082367875863433681332203403145435568316851327593401208105741076214120093531),
             uint256(8495653923123431417604973247489272438418190587263600148770280649306958101930)]
        ];

        uint256[2][2] memory delta = [
            [uint256(15792935853340806678541013381236318957525297919032586847243418110990829175574),
             uint256(6270982721560078223710675548946658623431242131309150325368548470725422924278)],
            [uint256(5417747995245839142507193961378167256446211105957420991676709608916407799877),
             uint256(12618417429723660274849279621605746554718616322161197798238886403862908372775)]
        ];

        // IC points for 2 public inputs (threshold, commitment)
        uint256[2][] memory ic = new uint256[2][](3);
        ic[0] = [
            uint256(10378135837474478460620464632455258028049008296913588133072760774368897943674),
            uint256(17507773511028576401554235685832436646795063431492176864637841356341846548533)
        ];
        ic[1] = [
            uint256(3125674560301784404012638097642365033871446711040183509403191186767986437600),
            uint256(11280427027174520751550264199503656097825639246826311845971817383100601513234)
        ];
        ic[2] = [
            uint256(6734726672255423786775157509470369691770481756273187188387361047720157490982),
            uint256(15717810961147472403549612059851035472285228238395046593226801399058876297477)
        ];

        console.log("Uploading VK to ReputationLimits:", reputationLimitsAddr);

        vm.startBroadcast(deployerPrivateKey);

        ReputationLimits reputationLimits = ReputationLimits(reputationLimitsAddr);
        reputationLimits.setVerificationKey(alpha, beta, gamma, delta, ic);

        vm.stopBroadcast();

        console.log("VK uploaded successfully");
    }
}

/**
 * @title DeployWithVK
 * @notice Full deployment including VK setup (for test VK)
 */
contract DeployWithVK is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);

        console.log("Deploying with test VK from:", deployer);

        vm.startBroadcast(deployerPrivateKey);

        // Deploy contracts
        AgentRegistry registry = new AgentRegistry(deployer);
        KamiyoVault vault = new KamiyoVault(address(registry), deployer);
        ReputationLimits reputationLimits = new ReputationLimits(address(registry), deployer);
        registry.setVault(address(vault));

        // Upload test VK (all zeros - for testing only)
        // In production, replace with actual VK from trusted setup
        uint256[2] memory alpha = [uint256(1), uint256(2)];
        uint256[2][2] memory beta = [[uint256(3), uint256(4)], [uint256(5), uint256(6)]];
        uint256[2][2] memory gamma = [[uint256(7), uint256(8)], [uint256(9), uint256(10)]];
        uint256[2][2] memory delta = [[uint256(11), uint256(12)], [uint256(13), uint256(14)]];

        uint256[2][] memory ic = new uint256[2][](3);
        ic[0] = [uint256(15), uint256(16)];
        ic[1] = [uint256(17), uint256(18)];
        ic[2] = [uint256(19), uint256(20)];

        reputationLimits.setVerificationKey(alpha, beta, gamma, delta, ic);

        vm.stopBroadcast();

        console.log("\n========== FULL DEPLOYMENT ==========");
        console.log("AgentRegistry:", address(registry));
        console.log("KamiyoVault:", address(vault));
        console.log("ReputationLimits:", address(reputationLimits));
        console.log("VK: test values (replace for production)");
        console.log("======================================\n");
    }
}

/**
 * @title Verify
 * @notice Verify deployed contracts
 */
contract Verify is Script {
    function run() external view {
        address registryAddr = vm.envAddress("AGENT_REGISTRY");
        address vaultAddr = vm.envAddress("KAMIYO_VAULT");

        AgentRegistry registry = AgentRegistry(payable(registryAddr));
        KamiyoVault vault = KamiyoVault(payable(vaultAddr));

        console.log("\n========== CONTRACT VERIFICATION ==========");

        // Verify AgentRegistry
        console.log("AgentRegistry:");
        console.log("  Address:", registryAddr);
        console.log("  Admin:", registry.admin());
        console.log("  Dispute Resolver:", registry.disputeResolver());
        console.log("  Vault:", registry.vault());
        console.log("  Total Agents:", registry.totalAgents());
        console.log("  Total Staked:", registry.totalStaked());
        console.log("  Min Stake:", registry.minStake());

        // Verify KamiyoVault
        console.log("\nKamiyoVault:");
        console.log("  Address:", vaultAddr);
        console.log("  Admin:", vault.admin());
        console.log("  Dispute Resolver:", vault.disputeResolver());
        console.log("  Agent Registry:", address(vault.agentRegistry()));
        console.log("  Position Count:", vault.positionCount());
        console.log("  Dispute Count:", vault.disputeCount());
        console.log("  Total Deposits:", vault.totalDeposits());
        console.log("  Dispute Fee:", vault.disputeFee());

        console.log("===========================================\n");
    }
}
